# Site
title:              Tulio Cruvinel Gomes
bio:                'Enthusiastic ethical hacker, Master in the art of reading pdfs and Opinions are my own.<br><br><b>YAR HAR FIDDLE DEE DEE</b>'
description:        "Do you have Brio?"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpeg'
background:         'assets/img/background.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
url:                https://0xNymerio.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   tuliocgomes

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              tulio.c.gomes@gmail.com
twitter:            0xNymerio
#facebook:           username
github-url:         0xNymerio
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          tuliocgomes
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@tuliocgomes'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
cv:                 tuliocgomes

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
